work_dir: /public/home/fan_lab/wangjie/utils/workflow_scripts/call_vntr_scripts
raw_sample_id_file: sample_ids/test_sample_ids.txt
project_dir: test_vntr_wrkf
call_vntr_shorter_job_type: "vntr"
call_vntr_job_type: "call_vntr"
clean_vntr_shorter_job_type: "cln-tr"
clean_vntr_job_type: "clean_vntr"
tr_batch_id: /public/home/fan_lab/wangjie/STR/ref_vntrs/straglr_input/splitted_repeats/batch_vntr_ids.txt
ref_tr_prefix: /public/home/fan_lab/wangjie/utils/workflow_scripts/call_vntr_scripts/ref_vntr/splitted/ref_vntr_
ref_tr_bed: /public/home/fan_lab/wangjie/utils/workflow_scripts/call_vntr_scripts/ref_vntr/60_straglr_ref_vntrs.bed
bam_dir: /public/home/fan_lab/wangjie/utils/workflow_scripts/call_vntr_scripts/bams
bam_suffix: _part_HiFi.sort.bam
applied_memory: 50gb
id_sep: .
max_str_len: 1992
min_str_len: 1
run_straglr_script: /public/home/fan_lab/wangjie/utils/workflow_scripts/call_vntr_scripts/scripts/run_straglr.pbs
clean_straglr_script: /public/home/fan_lab/wangjie/utils/workflow_scripts/call_vntr_scripts/scripts/clean_straglr_result.pbs
compress_raw_vntr_results_script: /public/home/fan_lab/wangjie/utils/workflow_scripts/call_vntr_scripts/scripts/compress_raw_vntr_results.pbs
submit_straglr_jobs_script: /public/home/fan_lab/wangjie/utils/workflow_scripts/call_vntr_scripts/scripts/submit_straglr_jobs.bin.sh
submit_clean_straglr_jobs_script: /public/home/fan_lab/wangjie/utils/workflow_scripts/call_vntr_scripts/scripts/submit_clean_straglr_jobs.bin.sh
submit_compress_straglr_jobs_script: /public/home/fan_lab/wangjie/utils/workflow_scripts/call_vntr_scripts/scripts/submit_compress_straglr_jobs.bin.sh
