#PBS -j oe

########################## Presets ##########################
set -ue
source "/public/home/fan_lab/wangjie/utils/shell_utils/utils.sh"

########################## Arguments ##########################
#arguments: work_dir file_list reheader_sample_file out_file threads

########################## softwares ##########################
export PATH=/public/home/fan_lab/wangjie/miniconda3/envs/straglr/bin/:$PATH
bcftools=/public/home/fan_lab/wangjie/Programs/bcftools/bin/bcftools

########################## Change workdir ##########################
myprint "Working dir is: "${work_dir}
cd ${work_dir}

########################## Begin ##########################
# scripts
starttime=`date +'%Y-%m-%d %H:%M:%S'`
myprint "Begin to analysis"
myprint "Threads is $threads"
myprint "file_list is $file_list, total $(wc -l $file_list | awk '{print $1}' ) files"
myprint "reheader_sample_file is $reheader_sample_file"
myprint "out_file is $out_file"

# 根据file_list来merge, 并进行reheader
$bcftools merge -l $file_list --force-samples --merge id --threads $threads | bcftools reheader --samples $reheader_sample_file - | bgzip > $out_file

tabix -p vcf $out_file

# TODO 可以让用户输入多个文件

########################## Done ##########################

# 计时结束
endtime=`date +'%Y-%m-%d %H:%M:%S'`
start_seconds=$(date --date="$starttime" +%s); # 将时间转换成秒数
end_seconds=$(date --date="$endtime" +%s);

echo $start_seconds $end_seconds | awk '{total_sec=$2-$1; min=int(total_sec/60); lef_sec=total_sec%60; printf("Total time: %d minutes, %d seconds.\n", min, lef_sec); }'

myprint "Program is done"

