du -sh benckmark_vntr_softwares
du -sh bin
du -sh check_ACSF3
du -sh CoreQueue
du -sh epilepsy
du -sh genome
du -sh GIAB_trio
du -sh gnomad_LD
du -sh group_share_dir
du -sh HPGP
du -sh HXDL
du -sh miniconda3
du -sh Minority_90
du -sh others
du -sh perl5
du -sh Programs
du -sh PublicDB
du -sh Quartet_data
du -sh shared_data
du -sh singularity_images
du -sh software_tests
du -sh stdin.split
du -sh STR
du -sh test
du -sh tmp
du -sh utils
du -sh ZYQueue
